# Source-of-truth Slurm scrontab entries for this repo.

#SCRON -A dremel_lab
#SCRON -p standard
#SCRON -J cleanup_uuid_dir
#SCRON -t 00:15:00
#SCRON -D /project/dremel_lab/scripts
#SCRON -o /project/dremel_lab/scripts/logs/cleanup_uuid_dir-%j.out
#SCRON -e /project/dremel_lab/scripts/logs/cleanup_uuid_dir-%j.err
0 0 * * * /project/dremel_lab/scripts/bin/cleanup_uuid_dir --delete

#SCRON -A dremel_lab
#SCRON -p standard
#SCRON -J storage_usage
#SCRON -t 00:20:00
#SCRON -D /project/dremel_lab/scripts
#SCRON -o /project/dremel_lab/scripts/logs/storage_usage-%j.out
#SCRON -e /project/dremel_lab/scripts/logs/storage_usage-%j.err
0 1 * * * /project/dremel_lab/scripts/bin/storage_usage
